from pathlib import Path
p=Path('docs/development/roadmap.md');s=p.read_text().replace('状态：in progress（代码已写入，待 Claude 验证）。','状态：completed（本轮有界实现/取证已交付，正式24h门禁未完成），见 [完成记录](../completion-records/HXA-185.md)。').replace('完成实现不等于通过编译或设备验收，未记录完成。','本轮实际通过与失败边界以完成记录为准，不把API36功能中止或API29在途测试记为24h通过。').replace('依 accepted [ADR-PROVIDER-002]', '依历史决定（现已 superseded）[ADR-PROVIDER-002]')
s+='\n\n### HXA-189 第三轮审查复核与缺陷修复\n\n状态：in progress。所有者授权逐条复核 improvement-review-2026-09-10，并修复当前证据支持的缺陷。允许 runtime/proot-ipc、app/UI/权限入口及相应测试、scripts/CI/docs/AGENTS；保留并行测试，不操作Claude模拟器。修复PFD所有权释放、用户主动系统权限申请/设置入口、Provider空态导航及文案、文档状态/索引和统一主机门禁。架构搬迁、全套onboarding/主题、R8/发行与新增扫描器需按收益/验证条件独立分类，不把建议当bug。保持IPC与能力/审批边界，不新增依赖。验收：受影响JVM、双app及PRoot构建/lint、Spotless/Detekt，门禁脚本自测与实际执行；设备脚本/用例交接独占测试者，未执行不得宣称通过。\n';p.write_text(s)
p=Path('docs/development/verification-matrix.md');s=p.read_text().replace('\n## HXA-185 验证结果','\n| HXA-189 | 审查逐条复核；PFD释放、权限/导航/文案、文档/CI门禁 | 进行中；JVM、构建/lint与脚本验证，设备结果单列 |\n\n## HXA-185 验证结果',1);s=s.replace('[run-index](../../build/emulator-verification/run-index.json)','本地忽略制品 `build/emulator-verification/run-index.json`');p.write_text(s)
p=Path('runtime/proot-ipc/src/main/kotlin/com/helix/runtime/proot/ipc/PfdManifestChannel.kt');s=p.read_text().replace('import java.io.FileOutputStream\n','').replace('            FileOutputStream(writeEnd.fileDescriptor).use { it.write(bytes) }','            ParcelFileDescriptor.AutoCloseOutputStream(writeEnd).use { it.write(bytes) }').replace('            readAll(ParcelFileDescriptor.AutoCloseInputStream(readEnd), out)','            ParcelFileDescriptor.AutoCloseInputStream(readEnd).use { readAll(it, out) }');p.write_text(s)
p=Path('app/src/main/kotlin/com/helix/app/ui/ExtensionsScreen.kt');s=p.read_text().replace('        authoring?.let { SkillAuthoringSection(it) }\n        HorizontalDivider()','        authoring?.let {\n            SkillAuthoringSection(it)\n            HorizontalDivider()\n        }').replace('            SkillInstallationSection(authoring, installation)\n        }\n        HorizontalDivider()','            SkillInstallationSection(authoring, installation)\n            HorizontalDivider()\n        }');p.write_text(s)
p=Path('app/src/main/kotlin/com/helix/app/ui/ApprovalCardScreen.kt');s=p.read_text().replace('FieldLine("Safety Profile",','FieldLine(stringResource(R.string.approval_profile_label),').replace('        "Provider/MCP",','        stringResource(R.string.approval_provider_label),');p.write_text(s)
for lang in ['values','values-zh-rCN','values-en']:
 p=Path('app/src/main/res')/lang/'strings.xml';s=p.read_text();import re
 note='Advanced shows additional capability controls. Switching profiles does not grant system permissions, install a Runtime, start Root, or approve tool calls. Enable each capability explicitly and choose its scope.' if lang=='values-en' else 'Advanced 显示额外能力的设置入口。切换配置不会自动授予系统权限、安装 Runtime、启动 Root 或批准工具调用；请按需启用各项能力并选择作用范围。'
 s=re.sub(r'(<string name="settings_advanced_m2_note">).*?(</string>)',lambda m:m[1]+note+m[2],s)
 entries={'approval_profile_label':('权限配置','Permission profile'),'approval_provider_label':('模型服务／MCP','Provider / MCP'),'chat_setup_provider':('配置模型服务','Set up a provider')}
 s=s.replace('</resources>',''.join(f'    <string name="{k}">{v[1 if lang=="values-en" else 0]}</string>\n' for k,v in entries.items())+'</resources>');p.write_text(s)
p=Path('AGENTS.md');s=p.read_text().replace('HXA-077 remains the mandatory SDK/transport/Android Spike, and HXA-078/079 cannot start until it records a viable implementation choice','HXA-077 records the SDK/transport/Android Spike; use the completed HXA-078/079 production contracts rather than restarting their historical enablement gates').replace('Git Workspace/UI/transport work reads proposed `docs/adr/workspace/003-git-boundaries.md`','Git Workspace/UI/transport work reads accepted `docs/adr/workspace/003-git-boundaries.md`');p.write_text(s)
p=Path('docs/adr/workspace/003-git-boundaries.md');s=p.read_text().replace('Status 仍为 proposed，待所有者决定','当时为 proposed；当前状态以文件头及 Decision 为准');p.write_text(s)
p=Path('docs/completion-records/HXA-088.md');s=p.read_text();s=s.replace('ADR-WORKSPACE-003 保持 proposed','ADR-WORKSPACE-003 在本次交付时保持 proposed（后续决定见 [当前ADR-WORKSPACE-003](../adr/workspace/003-git-boundaries.md)）');p.write_text(s)
