from pathlib import Path
base=Path('feature/browser/src/androidTest')
p=base/'kotlin/com/helix/feature/browser/webview/WebViewResourceLifecycleDeviceTest.kt'
s=p.read_text().replace('class WebViewResourceLifecycleDeviceTest {','class WebViewResourceLifecycleDeviceTest : BrowserResourceTestHost() {');p.write_text(s)
p=base/'AndroidManifest.xml';s=p.read_text().replace('<application android:usesCleartextTraffic="true">','<application android:usesCleartextTraffic="true">\n        <activity android:name="com.helix.feature.browser.webview.BrowserResourceTestActivity" android:exported="false" />');p.write_text(s)
s=Path('runtime/quickjs/src/androidTest/kotlin/com/helix/runtime/quickjs/QuickJsDeviceTestHost.kt').read_text().replace('com.helix.runtime.quickjs','com.helix.feature.browser.webview').replace('QuickJsDeviceTestHost','BrowserResourceTestHost').replace('QuickJsTestActivity','BrowserResourceTestActivity').replace('helix.quickjs.headless','helix.browser.resources.headless').replace('Helix QuickJS test\\nRunning isolated execution checks…','Helix browser resource test\\nRunning lifecycle checks…')
s=s.replace('import org.junit.Before','import org.junit.Before\nimport org.junit.Rule\nimport org.junit.rules.TestName').replace('    private var host: Activity? = null','    private var host: Activity? = null\n\n    @get:Rule\n    val resourceTestName = TestName()').replace('        // Explicit diagnostic comparison only;', '        // Preserve the separately driven legacy soak/control lifecycle contract.\n        if (resourceTestName.methodName in setOf("continuousResourceSoak", "rawPlatformWebViewLifecycleControl")) return\n        // Explicit diagnostic comparison only;')
(base/'kotlin/com/helix/feature/browser/webview/BrowserResourceTestHost.kt').write_text(s)
p=Path('scripts/debug/2026-09-10/run-physical-library-regression.py');s=p.read_text().replace("p.add_argument('--test',", "p.add_argument('--apk-metadata', type=Path, help='Explicit isolated build metadata, requires one module and SHA')\np.add_argument('--apk-sha256', help='Expected SHA for explicitly selected APK')\np.add_argument('--instrument-arg', nargs=2, action='append', default=[])\np.add_argument('--test',").replace("'runtime/quickjs'], default=", "'runtime/quickjs','tools/root'], default=").replace("assert not a.test or len(a.modules)==1", "assert not a.test or len(a.modules)==1\nassert not a.apk_metadata or (len(a.modules)==1 and a.apk_sha256)").replace("meta_path=Path(module)/", "meta_path=a.apk_metadata or Path(module)/").replace("'com.helix.runtime.'))", "'com.helix.runtime.','com.helix.tools.'))").replace("            if module=='feature/browser':assert", "            if a.apk_sha256:assert row['apkSha256']==a.apk_sha256\n            if module=='feature/browser' and not a.apk_metadata:assert").replace("                proc=subprocess.Popen", "                diagnostic += [part for pair in a.instrument_arg for part in ('-e', *pair)]\n                proc=subprocess.Popen")
p.write_text(s)
