from pathlib import Path
p=Path('app/src/androidTest/kotlin/com/helix/app/ui/GoalModelReportFlowDeviceTest.kt');s=p.read_text().replace('androidx.compose.ui.test.junit4.v2.AndroidComposeTestRule<androidx.test.ext.junit.rules.ActivityScenarioRule<MainActivity>, MainActivity>','androidx.compose.ui.test.junit4.AndroidComposeTestRule<*, *>');s=s.replace('chat.continueGoal(goal, "Answer 2 + 2. This is the entire task. Report your Goal status using goal.report, then answer briefly.")','chat.continueGoal(goal,\n            "Answer 2 + 2. This is the entire task. " +\n                "Report your Goal status using goal.report, then answer briefly.")');s=s.replace('assertTrue(storage.toolCalls.listByTurn(turns.single().id).any { it.name == "goal.report" && it.state == "COMPLETED" })','assertTrue(storage.toolCalls.listByTurn(turns.single().id).any {\n            it.name == "goal.report" && it.state == "COMPLETED"\n        })');p.write_text(s)
p=Path('app/src/main/kotlin/com/helix/app/goal/GoalReportTool.kt');s=p.read_text().replace('"""{"type":"object","properties":{"status":{"type":"string","enum":["complete","in_progress","blocked"]},"summary":{"type":"string","minLength":1,"maxLength":4096}},"required":["status","summary"],"additionalProperties":false}"""','''"""{
            "type":"object",
            "properties":{
                "status":{"type":"string","enum":["complete","in_progress","blocked"]},
                "summary":{"type":"string","minLength":1,"maxLength":4096}
            },
            "required":["status","summary"],"additionalProperties":false
        }"""''');s=s.replace('            override fun execute(', '            @Suppress("ReturnCount") // Explicit ownership and cancellation rejection boundaries.\n            override fun execute(')
s=s.replace('if (run == null || run.endedAt != null || storage.goals.resolve(run.goalId).state != "RUNNING" ||\n                    storage.turns.resolve(requireNotNull(call.turnId)).sessionId != call.sessionId\n                )', 'val active = run != null && run.endedAt == null\n                val owned = call.turnId?.let { storage.turns.resolve(it).sessionId == call.sessionId } == true\n                if (!active || !owned || storage.goals.resolve(requireNotNull(run).goalId).state != "RUNNING")')
s=s.replace('internal fun HelixStorage.goalModelReport(', '@Suppress("ReturnCount") // Reject stale, unsuccessful or malformed reports before consumption.\ninternal fun HelixStorage.goalModelReport(')
s=s.replace('if (status !in setOf("complete", "in_progress", "blocked") || summary.isBlank() || summary.length > 4096) return null','if (status !in setOf("complete", "in_progress", "blocked") ||\n        summary.isBlank() || summary.length > 4096\n    ) return null');p.write_text(s)
p=Path('app/src/main/kotlin/com/helix/app/goal/GoalReportContext.kt');s=p.read_text().replace('internal fun HelixStorage.goalReportContext(', '@Suppress("ReturnCount") // No goal context outside a current active durable binding.\ninternal fun HelixStorage.goalReportContext(');p.write_text(s)
p=Path('app/src/androidTest/kotlin/com/helix/app/provider/LoopbackModelServer.kt');s=p.read_text().replace('    private fun chatStream(', '    @Suppress("ReturnCount") // Independent report, tool-probe and plain-text fixture responses.\n    private fun chatStream(');p.write_text(s)
p=Path('core/agent/src/main/kotlin/com/helix/core/agent/Goal.kt');s=p.read_text().replace(' * explicit user continue with a real [GoalWakeReason]). The model reports semantic completion; the host checks execution state.', ' * explicit user continue with a real [GoalWakeReason]). The model reports semantic completion;\n * the host checks execution state.');p.write_text(s)
p=Path('app/src/main/kotlin/com/helix/app/chat/GoalRunSettlement.kt');s=p.read_text();a=s.index('        if (report != null) {');b=s.index('        storage.goalRuns.finish(',a);block=s[a:b];s=s[:a]+'        recordReport(goal, report)\n'+s[b:];marker='    private fun decision(';s=s.replace(marker,'''    private fun recordReport(goal: com.helix.core.agent.Goal, report: com.helix.app.goal.GoalModelReport?) {
'''+block+'''    }

'''+marker);p.write_text(s)
