package com.helix.core.model

/**
 * Domain identifiers for the single-device Helix model.
 *
 * Each identifier is a distinct [value class] over a validated opaque string. The distinct
 * runtime types prevent accidentally passing, for example, a [TurnId] where an [ExecutionId]
 * is expected. The string value is generated by an [IdGenerator], persisted verbatim in Room
 * (see architecture doc section 9.1 for the tables that own each ID), and correlated through
 * the audit chain `sessionId -> turnId -> modelCallId/toolCallId -> approvalId/executionId`.
 *
 * No prefix is enforced: type safety already comes from the value classes, and the
 * QuickJS `js_` instance-name convention is a platform detail owned by the QuickJS runtime.
 */
@JvmInline
value class SessionId(
    val value: String,
) {
    init {
        Identifier.requireValid("sessionId", value)
    }

    override fun toString(): String = value
}

@JvmInline
value class MessageId(
    val value: String,
) {
    init {
        Identifier.requireValid("messageId", value)
    }

    override fun toString(): String = value
}

@JvmInline
value class TurnId(
    val value: String,
) {
    init {
        Identifier.requireValid("turnId", value)
    }

    override fun toString(): String = value
}

@JvmInline
value class ModelCallId(
    val value: String,
) {
    init {
        Identifier.requireValid("modelCallId", value)
    }

    override fun toString(): String = value
}

@JvmInline
value class ToolCallId(
    val value: String,
) {
    init {
        Identifier.requireValid("toolCallId", value)
    }

    override fun toString(): String = value
}

@JvmInline
value class ToolResultId(
    val value: String,
) {
    init {
        Identifier.requireValid("toolResultId", value)
    }

    override fun toString(): String = value
}

@JvmInline
value class ApprovalId(
    val value: String,
) {
    init {
        Identifier.requireValid("approvalId", value)
    }

    override fun toString(): String = value
}

@JvmInline
value class ExecutionId(
    val value: String,
) {
    init {
        Identifier.requireValid("executionId", value)
    }

    override fun toString(): String = value
}

@JvmInline
value class ArtifactId(
    val value: String,
) {
    init {
        Identifier.requireValid("artifactId", value)
    }

    override fun toString(): String = value
}

@JvmInline
value class AuditEventId(
    val value: String,
) {
    init {
        Identifier.requireValid("auditEventId", value)
    }

    override fun toString(): String = value
}

@JvmInline
value class ProviderId(
    val value: String,
) {
    init {
        Identifier.requireValid("providerId", value)
    }

    override fun toString(): String = value
}

@JvmInline
value class RuntimeInstallId(
    val value: String,
) {
    init {
        Identifier.requireValid("runtimeInstallId", value)
    }

    override fun toString(): String = value
}

@JvmInline
value class PlanId(
    val value: String,
) {
    init {
        Identifier.requireValid("planId", value)
    }

    override fun toString(): String = value
}

@JvmInline
value class GoalId(
    val value: String,
) {
    init {
        Identifier.requireValid("goalId", value)
    }

    override fun toString(): String = value
}

@JvmInline
value class GoalRunId(
    val value: String,
) {
    init {
        Identifier.requireValid("goalRunId", value)
    }

    override fun toString(): String = value
}

@JvmInline
value class McpServerId(
    val value: String,
) {
    init {
        Identifier.requireValid("mcpServerId", value)
    }

    override fun toString(): String = value
}

@JvmInline
value class SkillId(
    val value: String,
) {
    init {
        Identifier.requireValid("skillId", value)
    }

    override fun toString(): String = value
}

@JvmInline
value class ExecutionTargetId(
    val value: String,
) {
    init {
        Identifier.requireValid("executionTargetId", value)
    }

    override fun toString(): String = value
}

@JvmInline
value class OperationId(
    val value: String,
) {
    init {
        Identifier.requireValid("operationId", value)
    }

    override fun toString(): String = value
}

@JvmInline
value class CorrelationId(
    val value: String,
) {
    init {
        Identifier.requireValid("correlationId", value)
    }

    override fun toString(): String = value
}

@JvmInline
value class ScopeId(
    val value: String,
) {
    init {
        Identifier.requireValid("scopeId", value)
    }

    override fun toString(): String = value
}

@JvmInline
value class WorkspaceId(
    val value: String,
) {
    init {
        Identifier.requireValid("workspaceId", value)
    }

    override fun toString(): String = value
}
