package com.helix.core.model

/**
 * Shared validation rules for opaque identifier values.
 *
 * Identifiers are generated by [IdGenerator] implementations, persisted verbatim in Room, and
 * correlated across audit chains. They must stay ASCII, free of separators and control
 * characters, and bounded in length so that malformed or adversarial values are rejected at
 * construction time.
 */
internal object Identifier {
    const val MAX_LENGTH = 64

    fun requireValid(
        kind: String,
        value: String,
    ) {
        require(value.isNotEmpty()) { "$kind must not be empty" }
        require(value.length <= MAX_LENGTH) { "$kind exceeds $MAX_LENGTH characters" }
        value.forEach { c ->
            require(isAllowedCharacter(c)) { "$kind contains invalid character" }
        }
    }

    fun isAllowedCharacter(c: Char): Boolean = isAsciiLetterOrDigit(c) || c == '_' || c == '-'

    fun isAsciiLetterOrDigit(c: Char): Boolean = c in 'a'..'z' || c in 'A'..'Z' || c in '0'..'9'
}

/**
 * Generates unique identifier values for the domain ID value classes in this module.
 *
 * Implementations must return values that satisfy [Identifier.requireValid]. Tests must use a
 * deterministic implementation (e.g. a sequential generator defined in the test) so that runs
 * are reproducible; the production implementation must not embed timestamps or
 * host-specific data.
 */
interface IdGenerator {
    fun next(): String
}

/**
 * Production [IdGenerator] based on 128 bits of cryptographically strong randomness.
 *
 * The result is a 32 character lowercase hex string, well inside [Identifier.MAX_LENGTH].
 * Collision probability is negligible for a single-device application.
 */
class RandomIdGenerator(
    private val random: java.util.Random = java.security.SecureRandom(),
) : IdGenerator {
    override fun next(): String {
        val bytes = ByteArray(RANDOM_BYTES)
        random.nextBytes(bytes)
        return Hex.encode(bytes)
    }

    private companion object {
        const val RANDOM_BYTES = 16
    }
}
