build:
  maxIssues: 0
  excludeCorrectable: false

config:
  validation: true
  warningsAsErrors: true
  checkExhaustiveness: false

complexity:
  LongParameterList:
    active: true
    functionThreshold: 8
    constructorThreshold: 10

style:
  MagicNumber:
    active: false
