package com.helix.app.export

import android.annotation.SuppressLint
import android.content.Context
import android.content.Intent
import android.net.Uri
import android.provider.DocumentsContract
import com.helix.core.storage.export.SessionExportRepository
import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.NonCancellable
import kotlinx.coroutines.currentCoroutineContext
import kotlinx.coroutines.ensureActive
import kotlinx.coroutines.sync.Mutex
import kotlinx.coroutines.sync.withLock
import kotlinx.coroutines.withContext
import java.io.File
import java.io.FileNotFoundException
import java.io.IOException
import java.util.UUID

/** Application-owned SAF delivery, available in both flavors and never registered as an agent tool. */
@SuppressLint("UseKtx") // KTX edit returns Unit; durable export transitions must check the Boolean commit result.
class SessionExportService(
    context: Context,
    private val repository: SessionExportRepository,
    private val appVersion: String,
) {
    private val resolver = context.applicationContext.contentResolver
    private val root = File(context.applicationContext.cacheDir, "session-exports")
    private val preferences = context.applicationContext.getSharedPreferences("session-export", Context.MODE_PRIVATE)
    private val mutex = Mutex()

    /** Call only with the new document returned by the user-initiated create-document picker. */
    suspend fun export(
        sessionId: String,
        newDocument: Uri,
        onProgress: (Long) -> Unit = {},
    ) {
        mutex.withLock {
            withContext(Dispatchers.IO) {
                check(preferences.getString("operation", null) == null) { "Interrupted export requires cleanup" }
                require(newDocument.scheme == "content")
                val operation = UUID.randomUUID().toString()
                val directory = File(root, operation)
                var delivered = false
                try {
                    val ownedGrant =
                        resolver.persistedUriPermissions.none {
                            it.uri == newDocument &&
                                it.isWritePermission
                        }
                    check(
                        preferences
                            .edit()
                            .putString(
                                "operation",
                                operation,
                            ).putString("target", newDocument.toString())
                            .putBoolean("releaseWriteGrant", ownedGrant)
                            .commit(),
                    )
                    if (ownedGrant) retainWriteGrant(newDocument)
                    val coroutine = currentCoroutineContext()
                    repository
                        .prepare(
                            sessionId,
                            directory,
                            appVersion,
                            SessionExportCredentials,
                            coroutine::ensureActive,
                        ).use {
                            SessionExportDelivery.write(resolver, newDocument, it, onProgress)
                        }
                    coroutine.ensureActive()
                    removeTemporary(directory)
                    releaseOwnedGrant(newDocument)
                    // Commit before declaring success; restart never resumes an unfinished export.
                    check(preferences.edit().clear().commit())
                    delivered = true
                } finally {
                    withContext(NonCancellable + Dispatchers.IO) {
                        if (!delivered) cleanup(directory, newDocument)
                    }
                }
            }
        }
    }

    /** Returns whether a prior operation was interrupted; performs cleanup only, never execution or re-export. */
    suspend fun cleanupInterrupted(): SessionExportRecovery =
        mutex.withLock {
            withContext(Dispatchers.IO) {
                val operation = preferences.getString("operation", null)
                var partialMayRemain = preferences.getBoolean("partialMayRemain", false)
                if (operation != null) {
                    // The only accepted directory identifier was generated by this service.
                    require(UUID.fromString(operation).toString() == operation)
                    val directory = File(root, operation)
                    val target = preferences.getString("target", null)?.let(Uri::parse)
                    partialMayRemain = cleanup(directory, target)
                }
                check(preferences.edit().remove("partialMayRemain").commit())
                SessionExportRecovery(operation != null, partialMayRemain)
            }
        }

    private fun cleanup(
        directory: File,
        target: Uri?,
    ): Boolean {
        removeTemporary(directory)
        val partialMayRemain = target != null && !cleanupTarget(target)
        if (target != null) releaseOwnedGrant(target)
        check(
            preferences
                .edit()
                .clear()
                .putBoolean("partialMayRemain", partialMayRemain)
                .commit(),
        )
        return partialMayRemain
    }

    private fun removeTemporary(directory: File) {
        if (directory.exists()) check(directory.deleteRecursively()) { "Export temporary cleanup failed" }
    }

    private fun retainWriteGrant(uri: Uri) {
        try {
            resolver.takePersistableUriPermission(uri, Intent.FLAG_GRANT_WRITE_URI_PERMISSION)
        } catch (_: SecurityException) {
            // Some providers offer only a transient grant; interrupted cleanup may then leave a visible partial file.
        }
    }

    private fun releaseOwnedGrant(uri: Uri) {
        if (preferences.getBoolean("releaseWriteGrant", false)) {
            try {
                resolver.releasePersistableUriPermission(uri, Intent.FLAG_GRANT_WRITE_URI_PERMISSION)
            } catch (_: SecurityException) {
                // The provider may not have offered a persistable grant, or deletion already revoked it.
            }
        }
    }

    private fun cleanupTarget(uri: Uri): Boolean =
        try {
            DocumentsContract.deleteDocument(resolver, uri)
        } catch (_: FileNotFoundException) {
            true // Already absent; no incomplete target remains.
        } catch (_: IOException) {
            false
        } catch (_: SecurityException) {
            false
        }
}

data class SessionExportRecovery(
    val interrupted: Boolean,
    val partialMayRemain: Boolean,
)
